title: Gustavo E. Medina Toledo (PhD)
description: A&S Postdoctoral Fellow, David A. Dunlap Department of Astronomy & Astrophysics, University of Toronto, Canada
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
header_pages:
  - contact.md
  - employment-history.md
  - research-highlights.md
  - recent-publications.md
